# .streamlit/secrets.toml
[admin]
username = "admin"
password = "admin123"
email = "admin@example.com"
# .streamlit/secrets.toml
[database]
DATABASE_URL = "sqlite:////mount/src/ecommercepython/data/ecommerce.db"

[stripe]
SECRET_KEY = "your_stripe_secret_key_here"
PUBLIC_KEY = "your_stripe_public_key_here"

[admin]
USERNAME = "admin"
PASSWORD = "admin123"
EMAIL = "admin@example.com"

[environment]
ENV = "development"
[general]
ENV = "development"