# .streamlit/secrets.toml
[admin]
username = "admin"
password = "admin123"
email = "admin@example.com"
# .streamlit/secrets.toml
[database]
DATABASE_URL = "sqlite:////mount/src/ecommercepython/data/ecommerce.db"

[stripe]
SECRET_KEY = "sk_test_51QjI3RK0I6u6klBligM7tZeWgEK1wOjljkHM3Yi1CojUq0UNCcLvrQjygv8Kc9es8SH6QgNKGGyzhHksvMyK54aH00Cz6LmQlr"
PUBLIC_KEY = "pk_test_51QjI3RK0I6u6klBlSt7uHW0VRwzAz8k61N4zTPpIXybkcNU9f3WTlHsQZaLDBPWjVhUtV2qUnRJlB7dbMEFeoBGs00Fp6SPq4q"

[admin]
USERNAME = "admin"
PASSWORD = "admin123"
EMAIL = "admin@example.com"

[environment]
ENV = "development"
[general]
ENV = "development"